name: Build APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Buildozer Action
        uses: ArtemSashko/buildozer-action@v1
        with:
          buildozer_version: master
          python_version: 3.11
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Boshkash_App_Mobile
          path: bin/*.apk
